# Generated by Django 4.1.5 on 2023-02-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('brand', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('screen', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='', max_length=100)),
                ('pressure', models.CharField(default='', max_length=100)),
                ('weight', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
